use_frameworks! :linkage => :static
use_modular_headers!
#inhibit_all_warnings!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => false,
:share_schemes_for_development_pods => true

platform :ios, '12.0'

target 'LoadPodspecError_Example' do
  
#  pod 'LoadPodspecError', :path => '../LoadPodspecError.podspec'
  
  pod 'LoadPodspecError', :path => '../LoadPodspecError.copy.podspec'

  target 'LoadPodspecError_Tests' do
    inherit! :search_paths

    
  end
end
